version: '3.8'

services:
  arcdata-site:
    build: .
    ports:
      - "8080:80"

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9091:9090"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana

  blackbox_exporter:
    image: prom/blackbox-exporter
    ports:
      - "9115:9115"

volumes:
  grafana-storage:

