- name: Installer et configurer monitoring
  hosts: all
  become: yes

  tasks:
    - name: Installer fail2ban et auditd
      apt:
        name:
          - fail2ban
          - auditd
        state: present

    - name: Activer fail2ban
      service:
        name: fail2ban
        state: started
        enabled: yes
