global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]  # test HTTP pour vérifier la réponse 200
    static_configs:
      - targets:
          - http://arcdata-site:80   # cible dans le réseau Docker
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115  # adresse du blackbox exporter dans Docker

  - job_name: 'arcdata-site'
    metrics_path: /
    static_configs:
      - targets: ['arcdata-site:80']

