- name: Configurer UFW (pare-feu)
  hosts: all
  become: yes

  tasks:
    - name: Autoriser SSH
      ufw:
        rule: allow
        port: 22
        proto: tcp

    - name: Autoriser HTTP/HTTPS
      ufw:
        rule: allow
        port: "{{ item }}"
        proto: tcp
      loop:
        - 80
        - 443

    - name: Activer UFW
      ufw:
        state: enabled
